web:
  image: nginx:alpine
  volumes:
   - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
   - ./web/nginx.conf.d:/etc/nginx/conf.d:ro
   - ./web/docroot:/usr/share/nginx/html:ro
   - /var/log/nginx
  command: nginx -g "daemon off;" -c /etc/nginx/nginx.conf
  ports:
   - 80

proxy:
  image: nginx:alpine
  volumes:
   - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
  links:
   - web:web
  ports:
   - 80
